{
  "hash": "c057a773a3b87cc6d19e14f4f7c6009b",
  "result": {
    "markdown": "---\ntitle: \"Research Question 2\"\n---\n\n\n**Research Question 2:**\n\nHow do factors like high-caloric food intake, smoking habits, vegetable intake and technology dependency correlate with weight?\n\n**Methodology:**\n\nThe above research question can be solved by using multilinear regression and variable selection.Adjusted R-square values is used as a criterion to perform the variable selection.\n\n**The statistical analysis of this dataset involves several steps:**\n\n-   **Data Loading:**\n\nFirstly,we need to load the CSV file.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlibrary(ggplot2)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.3.3\n```\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'car' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: carData\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'carData' was built under R version 4.3.3\n```\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlibrary(caret)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'caret' was built under R version 4.3.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: lattice\n```\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlibrary(MASS)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:MASS':\n\n    select\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:car':\n\n    recode\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ndata <- read.csv(\"C:\\\\Users\\\\arava\\\\OneDrive\\\\Desktop\\\\STAT515\\\\modified_obesity_data.csv\")\n```\n:::\n\n\n-   **Data Preprocessing:**\n\nThis step involves data cleaning where rows with missing values are deleted and categorical variables are converted into dummy numerical variables.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\ndata <- na.omit(data)\ndata$Highcaloric_food <- as.numeric(data$Highcaloric_food == \"yes\")\ndata$Smoking_Habit <- as.numeric(data$Smoking_Habit == \"yes\")\n```\n:::\n\n\n-   **Model Building:**\n\nWe build a linear model with Highcaloric_food, Smoking_Habit, Vegetable_intake and Technology_dependency as predictors and Weight as the dependent variable.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nlm_model <- lm(Weight ~ Highcaloric_food + Vegetable_intake + Smoking_Habit + Technology_dependency, data = data)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nstepwise_adj_r2 <- function(model, data) {\n  current_adj_r2 <- summary(model)$adj.r.squared\n  predictors <- names(coef(model))\n  best_model <- model\n  improvement <- TRUE\n  \n  while (improvement) {\n    improvement <- FALSE\n    best_adj_r2 <- current_adj_r2\n    \n    for (predictor in predictors[-1]) { \n      formula <- as.formula(paste(\"Weight ~\", paste(setdiff(predictors[-1], predictor), collapse = \" + \")))\n      candidate_model <- lm(formula, data = data)\n      candidate_adj_r2 <- summary(candidate_model)$adj.r.squared\n      \n      if (candidate_adj_r2 > best_adj_r2) {\n        best_adj_r2 <- candidate_adj_r2\n        best_model <- candidate_model\n        improvement <- TRUE\n      }\n    }\n    \n    if (improvement) {\n      current_adj_r2 <- best_adj_r2\n      predictors <- names(coef(best_model))\n    }\n  }\n  \n  return(best_model)\n}\n```\n:::\n\n\n-   **Variable Selection:**\n\nAfter building  a model the next step is to perform Stepwise regression which is a variable selection technique by taking Adjusted R-squared values as a criterion to improve the model fitting.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nfinal_model <- stepwise_adj_r2(lm_model, data)\n```\n:::\n\n\n-   **Displaying the Outputs and Plots:**\n\n After performing stepwise selection the summary of the final model is printed which gives the coefficients, significance levels, and statistics like R-squared values and F-statistics.We also print the coefficient plot, residual plot and variable Importance plot.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\nsummary_final_model <- summary(final_model)\nprint(summary_final_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Weight ~ Highcaloric_food + Vegetable_intake + Smoking_Habit + \n    Technology_dependency, data = data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-55.505 -17.647   0.165  15.725  78.498 \n\nCoefficients:\n                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            42.3267     3.0838  13.726  < 2e-16 ***\nHighcaloric_food       23.1905     1.7077  13.580  < 2e-16 ***\nVegetable_intake       10.6626     1.0326  10.326  < 2e-16 ***\nSmoking_Habit           8.3548     4.0203   2.078 0.037820 *  \nTechnology_dependency  -3.0029     0.9027  -3.327 0.000895 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 24.54 on 2053 degrees of freedom\nMultiple R-squared:  0.1283,\tAdjusted R-squared:  0.1266 \nF-statistic: 75.55 on 4 and 2053 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n**Summary of the model:**\n\n-   **Residuals:**\n\nResiduals are the differences between the observed values of the dependent variable (Weight) and the values predicted by the model.\n\n**Min**\n\nThe model underpredicted this observation by 55.505 units, given the smallest residual as -55.505.\n\n**First Quartile**\n\nFor a quarter of the data, the model's predictions are around 17.647 units too high, as indicated by 25% of the residuals being smaller than -17.647.\n\n**Median**\n\nThe median residual is very close to 0 (0.165), indicating that the model's predictions are generally accurate, as half of the residuals are below this value and half are above.\n\n**Third Quartile**\n\nMost observations have the model's prediction within about 15.725 units of the actual values, as indicated by the 75% of residuals being smaller than 15.725**.**\n\n**Max**\n\nThe greatest residual, which is 78.498 units, indicates that the highest underprediction of the model for any given observation is 78.498 units.\n\n-   **Coefficients:**\n\nThe predictors' coefficients indicate the expected rise in the dependent variable (weight) for each unit increase in the predictor, assuming no change in the other predictors.\n\n**Intercept**\n\nThe expected weight is about 42.33 units when all predictors are zero.\n\n**Highcaloric_food**\n\nIn comparison to not consuming high-calorie food, there is an average weight rise of 23.19 units linked to high-calorie food consumption\n\n**Vegetable_intake**\n\nWeight increases by around 10.66 units for every unit increase in vegetable intake.\n\n**Smoking_Habit**\n\nThe average weight rise of smokers  is 8.35 units higher than that of non-smokers.\n\n**Technology_dependency**\n\nWeight drops by 3.00 units for every unit increase in technological dependency.\n\n-   **Statistical Significance(Pr(\\>\\|t\\|)):**\n\n    It provides the p values to determine whether the model is statistically significant or not.Significance level(alpha) is generally set to 0.05. The null hypothesis states that no effect or no difference between groups whereas the alternative hypothesis stating that there is a  difference between groups.If the p\\< alpha(0.05)  the model is considered statistically significant, and the null hypothesis is rejected in favor of the alternative hypothesis.From the summary we can see that p values of all the predictors \\< 0.05 therefore suggesting that the model is statistically significant.\n\n-   **Residual Standard Error:**\n\n    This indicates how much the expected values differ from the actual values on an average.The deviation of the model is around 24.54 weight units.\n\n-   **Multiple R-squared (0.1283) and Adjusted R-squared (0.1266):**\n\n    The model accounts for approximately 12.83% of the variance observed in the dependent variable, weight.When several predictors are present, the adjusted measure becomes more accurate since it accounts for approximately 12.66% of the variation in the model.\n\n-   **F-statistic and its p-value:**\n\n```         \nThis tests whether at least one predictor variable has a non-zero coefficient or not. The less p values states that the model is statistically significant.\n```\n\nIn conclusion we can say that the model is statistically significant but with an Adjusted R-squared value of 0.1266 we can say that there is a small variance in the weight.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Coefficient plot\ncoef_plot_adj_r2 <- ggplot(data = as.data.frame(coef(summary(final_model))), aes(x = rownames(coef(summary(final_model))), y = Estimate)) +\n  geom_bar(stat = \"identity\", fill = \"orange\", color = \"black\") +\n  labs(title = \"Coefficients of Predictors (Adjusted R-Squared Criterion)\", x = \"Predictors\", y = \"Coefficient Estimate\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\nprint(coef_plot_adj_r2)\n```\n\n::: {.cell-output-display}\n![](Research-Question-2_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe above bar chart displays the coefficient estimates for each predictor in the regression model.\n\n**Implications of the Coefficients:**\n\n**Positive coefficients**(Highcaloric_food, Vegetable_intake, Smoking_Habit) shows a direct relationship with weight, where increases in these variables are associated with increases in weight.\n\n**Negative coefficient** (Technology_dependency) shows an inverse relationship, where increases in this variable are associated with decreases in weight.\n\n**Conclusion:**\n\nThe strength and influence of each predictor on the dependent variable weight, are shown by the relative sizes of the bars. Highcaloric_food shows the most dominant effect, followed by vegetable_intake suggesting that these variables are the most important contributors to the difference in weight shown in your data. The figure clearly illustrates the various effects of dietary and lifestyle choices on weight and offers a visual representation of the regression results that were previously presented.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Residual plot\nresidual_plot_adj_r2 <- ggplot(data, aes(x = fitted(final_model), y = residuals(final_model))) +\n  geom_point(color = \"black\") +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  labs(title = \"Residual Plot (Adjusted R-Squared Criterion)\", x = \"Fitted Values\", y = \"Residuals\") +\n  theme_minimal()\nprint(residual_plot_adj_r2)\n```\n\n::: {.cell-output-display}\n![](Research-Question-2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe residual shows the residuals on the vertical axis (the differences between observed and predicted values) plotted against the fitted values(predicted) on the horizontal axis.The dashed red line at zero indicates perfect prediction by the model.The residual plot shows residuals scattered randomly around zero, mostly on the positive side. However, distinct clusters around certain predictions, such as 80 and 100, suggest possible missing nonlinear effects or interactions in the model.Extreme outliers, both above and below the zero line, require investigation for potential data errors.Clear patterns, such as vertical clustering, indicate potential issues like incorrect assumptions about variable relationships or overrepresentation of predictor levels in certain ranges.\n\nIn conclusion,the residual plot is a tool for diagnostic checking. It helps in assessing whether the assumptions of linear regression (linearity, independence, constant varience, and normality of residuals) are reasonably satisfied or if further model improvements are needed or not.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show the code\"}\n# Variable importance plot\nvar_importance_adj_r2 <- ggplot(data = as.data.frame(varImp(final_model)), aes(x = rownames(varImp(final_model)), y = Overall)) +\n  geom_bar(stat = \"identity\", fill = \"cornsilk\", color = \"black\") +\n  labs(title = \"Variable Importance\", x = \"Predictors\", y = \"Importance\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\nprint(var_importance_adj_r2)\n```\n\n::: {.cell-output-display}\n![](Research-Question-2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nThe Variable Importance bar chart visually represents the relative importance of different predictors in the regression model. Highcaloric_food predictor has the highest importance in the model, indicating that it has a potential effect on the dependent variable (weight). This aligns with the earlier regression output where the coefficient for high-caloric food intake was significantly positive, suggesting a strong association with increased weight. Smoking_habit shows the least importance compared to all the predictors. This lesser importance reflects its relatively lower coefficient and it was also marginally significant in the regression analysis (p-value close to the typical significance threshold of 0.05).\n\nIn conclusion,this plot ranks the predictors by their influence on the model's ability to predict weight.Predictors with higher bars are more critical for the model, meaning changes in these predictors are associated with more significant changes in weight.\n",
    "supporting": [
      "Research-Question-2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}